Repository perennialAutodidact/memory-snap, pull requests merged in 2023-11, with the labels that each got.

#66 5 tilegrid component removed matched tiles
  packages/frontend/package.json
  packages/frontend/src/components/Game/GameBoard/Tile/index.jsx
  packages/frontend/src/components/Game/GameBoard/Tile/index.test.jsx
  packages/frontend/src/components/Game/GameBoard/Tile/style.scss
  packages/frontend/src/components/Game/GameBoard/TileGrid/index.jsx
  packages/frontend/src/components/Game/GameBoard/index.test.jsx
  packages/frontend/src/components/providers/game/index.jsx
  packages/frontend/src/contexts/game/index.js
  packages/frontend/src/contexts/game/reducer/index.js
  packages/frontend/src/contexts/game/reducer/index.test.js
  packages/frontend/src/helpers/tests.jsx
  yarn.lock
Labels: frontend, gameplay, ready for review

#71 64 eslint change unused imports from errors to warnings
  packages/backend/.eslintrc.json
  packages/backend/package.json
  packages/frontend/.eslintrc.json
  packages/frontend/package.json
  yarn.lock
Labels: devops, ready for review

#74 65 eslint setup pre push hook for testinglinting
  .eslintignore
  .husky/pre-commit
  .husky/pre-push
  .prettierignore
  .stylelintignore
  .stylelintrc.json
  README.md
  package.json
  packages/backend/lint-staged.config.js
  packages/backend/package.json
  packages/frontend/lint-staged.config.js
  packages/frontend/package.json
  packages/frontend/src/components/Game/GameBoard/Tile/index.test.jsx
  packages/frontend/src/components/Game/GameBoard/Tile/style.scss
  packages/frontend/src/components/Game/GameBoard/TileGrid/index.jsx
  packages/frontend/src/components/Game/GameBoard/index.test.jsx
  packages/frontend/src/contexts/game/reducer/index.test.js
  packages/frontend/src/helpers/createTilesFromPhotos.test.jsx
  packages/frontend/src/styles/index.scss
  yarn.lock
Labels: devops, ready for review

#70 69 add consolelog to eslint rules
  packages/backend/.eslintrc.json
  packages/backend/app.js
  packages/frontend/.eslintrc.json
Labels: devops, ready for review

#80 43 setup sockets
  packages/backend/.eslintrc.json
  packages/backend/__test__/helpers.js
  packages/backend/app.js
  packages/backend/controllers/express/index.js
  packages/backend/controllers/express/photosController.js
  packages/backend/controllers/socketio/gameController/index.js
  packages/backend/controllers/socketio/index.js
  packages/backend/controllers/socketio/index.test.js
  packages/backend/jest.config.js
  packages/backend/jsconfig.json
  packages/backend/package.json
  packages/frontend/.eslintignore
  packages/frontend/.eslintrc.json
  packages/frontend/src/hooks/useGameContext/index.test.jsx
  packages/frontend/src/styles/index.scss
  yarn.lock
Labels: backend, devops, ready for review
